---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

#이상점의 종류

이상점 탐지는 {tsoutliers} 패키지도 있고, {changepoint} 패키지도 있다.

{changepoint} 패키지를 이용한 이상점 탐지 방법을 알아보고자 한다.

```{r}
if(!require(changepoint)) install.packages('changepoint')
library(changepoint)
```

#changepoint 패키지의 대표 알고리즘은 이진분할 (Binary Segmentation), PELT(Pruned Exact Linear Time) 등이 있음
*cpt.mean(data,...)
*cpt.var(data,...)
*cpt.meanvar(data,...)

#평균의 변화 탐지

```{r}
set.seed(100)
y<-c(rnorm(100,0,1), rnorm(100,5,1), rnorm(100,2,1))
ansmean<-cpt.mean(y, method='PELT')
cpts(ansmean)    #변화점을 알려준다.
```
```{r}
plot(ansmean, cpt.col='blue')
```



#분산의 변화 탐지

```{r}
set.seed(100)
x<-c(rnorm(100, 0, 1), rnorm(100, 0,10), rnorm(100, 0,2))
ansvar=cpt.var(x, method='PELT')
cpts(ansvar)    #변화 시작점을 알려준다.
```
```{r}
plot(ansvar)
```


#평균과 분산의 동시 변화 탐지
```{r}
set.seed(100)
z<-c(rnorm(100,0,1), rnorm(100,2,10))
ansmeanvar<-cpt.meanvar(z, method='PELT')
cpts(ansmeanvar)    #변화의 시작점을 알려 줌

```
```{r}
plot(ansmeanvar, cpt.width=3)
```


